name: 01 - Building Blocks
on:
  - push
  - workflow_dispatch
jobs:
  
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"

  say-goodbye:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Exiting with code 0"
          exit 0
        name: "Exit with code 0"

      - run: echo "Goodbye!"
        name: "Say goodbye"
