name: "02 - Workflow Events"

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
   - cron: '0 0 * * SUN'
  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "Show the trigger"
        run: |
          echo "${{github.event_name}}"